# Generated by Django 4.1.6 on 2023-04-15 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("chude", models.CharField(max_length=200)),
                ("cauhoi", models.CharField(max_length=500)),
                ("traloi", models.CharField(max_length=5000)),
            ],
        ),
    ]
